import { PrismaClient, AnimalCategory, Habitat, Biome, Difficulty, Temperament, DietType, PlantCategory, LightLevel, GrowthRate, PlantPlacement, ProductCategory, PriceRange, CompatibilityLevel } from '@prisma/client';

const prisma = new PrismaClient();

const img = (type: 'animal' | 'plant' | 'product', name: string) => {
  const colors = { animal: '#1a5490', plant: '#2d5a27', product: '#666666' };
  const bg = colors[type];
  const safeName = name.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect width="400" height="300" fill="${bg}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#ffffff" font-family="Arial, sans-serif" font-size="22" font-weight="bold">${safeName}</text></svg>`;
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
};

async function main() {
  console.log('Populating Aquascape databases with additional entries...');

  const newAnimals = [
    { name: 'Blue Tang', scientificName: 'Paracanthurus hepatus', category: AnimalCategory.FISH, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.SEMI_AGGRESSIVE, dietType: DietType.HERBIVORE, minTankSize: 75, tempMin: 75, tempMax: 82, phMin: 8.1, phMax: 8.4, maxSize: 12, lifespan: '8-12 years', origin: 'Indo-Pacific', imageUrl: img('animal', 'Blue Tang'), description: 'Iconic blue surgeonfish that needs plenty of swimming room and algae to graze.', careGuide: 'Stable marine parameters, large tank, plenty of live rock for grazing.', feedingGuide: 'Marine algae sheets, spirulina pellets, occasional mysis.', socialNeeds: 'Semi-aggressive; keep one per tank unless very large.', breedingInfo: 'Not bred in captivity.', commonDiseases: 'Marine ich, HLLE from poor nutrition.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Single tang in 75+ gallons.', specialConsiderations: 'Requires excellent filtration and swimming space.', tags: ['saltwater', 'surgeonfish', 'herbivore'] },
    { name: 'Royal Gramma', scientificName: 'Gramma loreto', category: AnimalCategory.FISH, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.CARNIVORE, minTankSize: 30, tempMin: 72, tempMax: 78, phMin: 8.1, phMax: 8.4, maxSize: 3, lifespan: '5-6 years', origin: 'Caribbean', imageUrl: img('animal', 'Royal Gramma'), description: 'Colorful purple-and-yellow reef fish that stays small and peaceful.', careGuide: 'Provide rock caves and stable reef parameters.', feedingGuide: 'Frozen mysis, brine shrimp, small marine pellets.', socialNeeds: 'Peaceful but territorial about its cave.', breedingInfo: 'Mouthbrooder; spawned in captivity.', commonDiseases: 'Marine ich.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'One per 30 gallons.', specialConsiderations: 'May chase similar-looking fish.', tags: ['saltwater', 'reef-safe', 'colorful'] },
    { name: 'Firefish Goby', scientificName: 'Nemateleotris magnifica', category: AnimalCategory.FISH, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.CARNIVORE, minTankSize: 20, tempMin: 72, tempMax: 78, phMin: 8.1, phMax: 8.4, maxSize: 3, lifespan: '3-5 years', origin: 'Indo-Pacific', imageUrl: img('animal', 'Firefish Goby'), description: 'Peaceful dartfish with a brilliant red tail that hovers near the rockwork.', careGuide: 'Provide a secure lid and plenty of hiding places.', feedingGuide: 'Frozen mysis, brine shrimp, small pellets.', socialNeeds: 'Peaceful. Often kept singly or in mated pairs.', breedingInfo: 'Difficult in captivity.', commonDiseases: 'Marine ich.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'One or a pair in 20+ gallons.', specialConsiderations: 'Jumps when startled — tight-fitting lid essential.', tags: ['saltwater', 'reef-safe', 'colorful'] },
    { name: 'Lawnmower Blenny', scientificName: 'Salarias fasciatus', category: AnimalCategory.FISH, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.HERBIVORE, minTankSize: 30, tempMin: 72, tempMax: 78, phMin: 8.1, phMax: 8.4, maxSize: 5, lifespan: '2-4 years', origin: 'Indo-Pacific', imageUrl: img('animal', 'Lawnmower Blenny'), description: 'Algae-grazing blenny with tons of personality and googly eyes.', careGuide: 'Mature tank with plenty of algae-covered live rock.', feedingGuide: 'Algae sheets, spirulina, vegetable-based foods once algae runs low.', socialNeeds: 'Peaceful; one per tank.', breedingInfo: 'Not bred in captivity.', commonDiseases: 'Starvation in algae-poor tanks.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'One per 30+ gallons.', specialConsiderations: 'Needs a mature tank with natural algae.', tags: ['saltwater', 'algae-eater', 'reef-safe'] },
    { name: 'Longfin Bannerfish', scientificName: 'Heniochus acuminatus', category: AnimalCategory.FISH, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 75, tempMin: 72, tempMax: 78, phMin: 8.1, phMax: 8.4, maxSize: 9, lifespan: '5-7 years', origin: 'Indo-Pacific', imageUrl: img('animal', 'Longfin Bannerfish'), description: 'Striking black-and-white fish with elongated dorsal fin.', careGuide: 'Large tank with open swimming and reef-safe decor.', feedingGuide: 'Frozen mysis, brine shrimp, marine flakes, nori.', socialNeeds: 'Peaceful; best kept singly or in pairs in large tanks.', breedingInfo: 'Not bred in captivity.', commonDiseases: 'Marine ich and refusal to feed in new tanks.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Single in 75+ gallons.', specialConsiderations: 'Needs a varied diet and stable conditions.', tags: ['saltwater', 'centerpiece', 'reef-safe'] },
    { name: 'Hammer Coral', scientificName: 'Euphyllia ancora', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 30, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 6, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Hammer Coral'), description: 'Large-polyp stony coral with branching hammer-shaped tentacles.', careGuide: 'Moderate light and flow. Leave space for sweeper tentacles.', feedingGuide: 'Photosynthetic, benefits from target feeding mysis and reef roids.', socialNeeds: 'Aggressive toward nearby corals with sweeper tentacles.', breedingInfo: 'Propagated by fragging branches.',     commonDiseases: 'Tissue recession from poor flow or parameter swings.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Place in lower to middle light with room around it.', specialConsiderations: 'Sweeper tentacles can sting neighbors 6+ inches away.', tags: ['coral', 'lps', 'advanced'] },
    { name: 'Zoanthids', scientificName: 'Zoanthus spp.', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 10, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 4, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Zoanthids'), description: 'Colorful colonial soft corals available in endless patterns.', careGuide: 'Low to moderate light and flow. Can spread quickly across rocks.', feedingGuide: 'Photosynthetic, occasional reef roids or phytoplankton.', socialNeeds: 'Peaceful but can overgrow nearby corals.', breedingInfo: 'Spreads by budding and can be fragged.', commonDiseases: 'Zoa pox, bacterial infections if stressed.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Easy beginner coral in any reef tank.', specialConsiderations: 'Some varieties contain palytoxin — handle carefully.', tags: ['coral', 'soft-coral', 'beginner'] },
    { name: 'Mushroom Coral', scientificName: 'Rhodactis / Discosoma spp.', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 10, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 3, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Mushroom Coral'), description: 'Low-light tolerant soft coral with round fleshy polyps.', careGuide: 'Very forgiving coral for new reef keepers.', feedingGuide: 'Photosynthetic, occasional fine particulate foods.', socialNeeds: 'Peaceful but can detach and move.', breedingInfo: 'Spreads by splitting.', commonDiseases: 'Few issues.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Great starter coral for low-flow areas.', specialConsiderations: 'Some mushrooms grow very large and shade neighbors.', tags: ['coral', 'soft-coral', 'beginner'] },
    { name: 'Duncan Coral', scientificName: 'Duncanopsammia axifuga', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.CARNIVORE, minTankSize: 20, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 4, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Duncan Coral'), description: 'Large-polyp stony coral with long flowing tentacles that sway in current.', careGuide: 'Moderate light and low to moderate flow.', feedingGuide: 'Target feed mysis, brine shrimp, or coral pellets 2-3 times weekly.', socialNeeds: 'Peaceful; tentacles generally do not sting far.', breedingInfo: 'Fragged by cutting heads from base.', commonDiseases: 'Tissue recession from too much flow or poor nutrition.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Middle to lower light placement.', specialConsiderations: 'Grows faster with regular feeding.', tags: ['coral', 'lps', 'colorful'] },
    { name: 'Altum Angelfish', scientificName: 'Pterophyllum altum', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.RIVER, difficulty: Difficulty.EXPERT, temperament: Temperament.PEACEFUL, dietType: DietType.CARNIVORE, minTankSize: 55, tempMin: 78, tempMax: 84, phMin: 5.5, phMax: 6.5, maxSize: 7, lifespan: '10-15 years', origin: 'South America', imageUrl: img('animal', 'Altum Angelfish'), description: 'Taller and more delicate than common angelfish; a showpiece for expert keepers.', careGuide: 'Very soft, acidic, warm water. Tall tank with excellent filtration.', feedingGuide: 'Frozen bloodworms, brine shrimp, high-quality carnivore pellets.', socialNeeds: 'Peaceful but may eat very small fish. Form pairs.', breedingInfo: 'Pairs lay eggs on vertical surfaces.', commonDiseases: 'Sensitive to transport and parameter swings.', waterChangeNeeds: '30-50% weekly', stockingRecommendations: 'Pair or small group in 55+ tall tanks.', specialConsiderations: 'Difficult to acclimate; wild-caught common.', tags: ['centerpiece', 'expert', 'sensitive'] },
    { name: 'Electric Blue Ram', scientificName: 'Mikrogeophagus ramirezi', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.RIVER, difficulty: Difficulty.ADVANCED, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 20, tempMin: 78, tempMax: 85, phMin: 5.5, phMax: 7, maxSize: 2.5, lifespan: '2-3 years', origin: 'South America', imageUrl: img('animal', 'Electric Blue Ram'), description: 'Bright blue selectively bred variant of the German blue ram.', careGuide: 'Warm soft acidic water, stable parameters, planted tank with caves.', feedingGuide: 'Small frozen foods, pellets, live foods.', socialNeeds: 'Forms pairs. Peaceful community fish.', breedingInfo: 'Cave spawner; both parents care for eggs.', commonDiseases: 'Sensitive to poor water and parasites.', waterChangeNeeds: '20-25% weekly', stockingRecommendations: 'Pair in 20+ gallons.', specialConsiderations: 'Inbred strains can be delicate; buy from quality sources.', tags: ['colorful', 'dwarf-cichlid', 'pair'] },
    { name: 'Ember Tetra', scientificName: 'Hyphessobrycon amandae', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.RIVER, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 10, tempMin: 75, tempMax: 82, phMin: 6, phMax: 7, maxSize: 1, lifespan: '2-4 years', origin: 'South America', imageUrl: img('animal', 'Ember Tetra'), description: 'Tiny glowing orange tetra perfect for nano planted tanks.', careGuide: 'Soft, acidic, planted water with gentle flow and dark substrate.', feedingGuide: 'Micro pellets, crushed flakes, baby brine shrimp.', socialNeeds: 'Schooling fish; keep in groups of 8-10+.', breedingInfo: 'Egg scatterer among fine-leafed plants.', commonDiseases: 'Ich when stressed by cool or poor water.', waterChangeNeeds: '10-20% weekly', stockingRecommendations: 'School of 10+ in a 10 gallon nano.', specialConsiderations: 'Tiny mouth — feed small foods.', tags: ['nano', 'schooling', 'colorful'] },
    { name: 'Rummynose Tetra', scientificName: 'Hemigrammus rhodostomus', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 20, tempMin: 75, tempMax: 82, phMin: 6, phMax: 7.5, maxSize: 2.5, lifespan: '5-8 years', origin: 'South America', imageUrl: img('animal', 'Rummynose Tetra'), description: 'Hardy schooling tetra with a bright red head and striped tail.', careGuide: 'Clean, warm, soft water; sensitive to ammonia and nitrite.', feedingGuide: 'Quality flakes, micro pellets, frozen daphnia and brine.', socialNeeds: 'Tight schooler; keep 8+ or they stress.', breedingInfo: 'Egg scatterer; requires very soft acidic water.', commonDiseases: 'Stress fading, ich.', waterChangeNeeds: '20-25% weekly', stockingRecommendations: 'School of 10+ in a 20 gallon planted tank.', specialConsiderations: 'Head color fades with poor water — a living water-quality gauge.', tags: ['schooling', 'colorful', 'indicator'] },
    { name: 'Celestial Pearl Danio', scientificName: 'Danio margaritatus', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 10, tempMin: 73, tempMax: 79, phMin: 6.5, phMax: 7.5, maxSize: 1, lifespan: '3-5 years', origin: 'Myanmar', imageUrl: img('animal', 'Celestial Pearl Danio'), description: 'Galaxy-spotted nano danio that looks like a tiny trout.', careGuide: 'Cool to warm, clean, planted water with gentle flow.', feedingGuide: 'Micro pellets, crushed flakes, baby brine shrimp, microworms.', socialNeeds: 'Peaceful; best in groups of 6-10.', breedingInfo: 'Spawns daily among moss; adults may eat eggs.', commonDiseases: 'Few; sensitive to warm stagnant water.', waterChangeNeeds: '10-20% weekly', stockingRecommendations: 'Group of 8+ in a 10 gallon planted tank.', specialConsiderations: 'Males spar without harm; provide plant cover.', tags: ['nano', 'schooling', 'colorful'] },
    { name: 'Chili Rasbora', scientificName: 'Boraras brigittae', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 5, tempMin: 68, tempMax: 82, phMin: 4, phMax: 7, maxSize: 0.8, lifespan: '4-8 years', origin: 'Borneo', imageUrl: img('animal', 'Chili Rasbora'), description: 'Vivid red micro-rasbora for blackwater nano tanks.', careGuide: 'Tannin-stained soft acidic water, leaf litter, dim light.', feedingGuide: 'Crushed flakes, micro pellets, baby brine, vinegar eels.', socialNeeds: 'Shy schooler; keep 10+ with own kind.', breedingInfo: 'Scatters eggs among moss; very tiny fry.', commonDiseases: 'Sensitive to hard alkaline water.', waterChangeNeeds: '10% weekly', stockingRecommendations: 'School of 10-15 in a 5-10 gallon blackwater tank.', specialConsiderations: 'Tiniest common aquarium fish — feed microscopic foods.', tags: ['nano', 'blackwater', 'schooling'] },
    { name: 'Siamese Algae Eater', scientificName: 'Crossocheilus siamensis', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.RIVER, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.HERBIVORE, minTankSize: 30, tempMin: 75, tempMax: 79, phMin: 6.5, phMax: 7, maxSize: 6, lifespan: '8-10 years', origin: 'Southeast Asia', imageUrl: img('animal', 'Siamese Algae Eater'), description: 'Best hair and black-brush algae eater in the hobby.', careGuide: 'Clean, well-oxygenated river-style tank with current.', feedingGuide: 'Algae, sinking wafers, blanched veggies, occasional frozen foods.', socialNeeds: 'Peaceful; keep singly or in small groups.', breedingInfo: 'Not bred in home aquariums.', commonDiseases: 'Few; sensitive to poor oxygen.', waterChangeNeeds: '20-25% weekly', stockingRecommendations: 'One per 30 gallons.', specialConsiderations: 'Distinguish from the aggressive Chinese algae eater lookalike.', tags: ['algae-eater', 'useful', 'river'] },
    { name: 'Honey Gourami', scientificName: 'Trichogaster chuna', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.WETLAND, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 15, tempMin: 72, tempMax: 82, phMin: 6, phMax: 7.5, maxSize: 2.5, lifespan: '4-8 years', origin: 'South Asia', imageUrl: img('animal', 'Honey Gourami'), description: 'Small, peaceful gourami with a warm honey-gold glow in males.', careGuide: 'Planted, calm water with floating plants and a lid.', feedingGuide: 'Flakes, micro pellets, frozen brine and daphnia.', socialNeeds: 'Peaceful; best as a male with 2-3 females.', breedingInfo: 'Male builds a bubble nest among floating plants.', commonDiseases: 'Dropsy and velvet in poor water.', waterChangeNeeds: '10-20% weekly', stockingRecommendations: 'Trio in a 15-20 gallon planted tank.', specialConsiderations: 'Shy; avoid fin-nipping tankmates.', tags: ['colorful', 'anabantid', 'beginner'] },
    { name: 'Panda Cory', scientificName: 'Corydoras panda', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 20, tempMin: 68, tempMax: 77, phMin: 6, phMax: 7.5, maxSize: 2, lifespan: '5-10 years', origin: 'South America', imageUrl: img('animal', 'Panda Cory'), description: 'Adorable black-and-white corydoras that shoals across the sand.', careGuide: 'Soft sand substrate, clean well-oxygenated water, planted cover.', feedingGuide: 'Sinking wafers, frozen bloodworms, pellets.', socialNeeds: 'Shoaling fish; keep in groups of 6+.', breedingInfo: 'Egg scatterer on glass and plants.', commonDiseases: 'Barbel erosion on sharp gravel.', waterChangeNeeds: '20-25% weekly', stockingRecommendations: 'Group of 6+ in a 20 gallon.', specialConsiderations: 'Use sand, not gravel, to protect barbels.', tags: ['bottom-dweller', 'shoaling', 'corydoras'] },
    { name: 'Clown Pleco', scientificName: 'Panaque maccus', category: AnimalCategory.FISH, habitats: [Habitat.FRESHWATER], biome: Biome.RIVER, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.HERBIVORE, minTankSize: 30, tempMin: 75, tempMax: 85, phMin: 6.5, phMax: 7.8, maxSize: 4, lifespan: '10-12 years', origin: 'Venezuela/Colombia', imageUrl: img('animal', 'Clown Pleco'), description: 'Small wood-eating pleco with striking striped pattern.', careGuide: 'Warm water, driftwood (essential for digestion), hides and current.', feedingGuide: 'Driftwood, veggie wafers, blanched zucchini, occasional frozen foods.', socialNeeds: 'Territorial with own kind; keep singly.', breedingInfo: 'Cave spawner; bred in captivity.', commonDiseases: 'Bloat from too much protein.', waterChangeNeeds: '20-25% weekly', stockingRecommendations: 'One per 30 gallons with multiple caves.', specialConsiderations: 'Requires real driftwood to graze — not a cleaner of algae.', tags: ['pleco', 'wood-eater', 'hidey'] },
    { name: 'Blue Velvet Shrimp', scientificName: 'Neocaridina davidi var. Blue', category: AnimalCategory.INVERTEBRATE, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 5, tempMin: 65, tempMax: 78, phMin: 6.5, phMax: 7.5, maxSize: 1.5, lifespan: '1-2 years', origin: 'Selectively bred', imageUrl: img('animal', 'Blue Velvet Shrimp'), description: 'Bright blue Neocaridina morph that pops against green plants.', careGuide: 'Stable, mature, planted water with moss and hiding spots.', feedingGuide: 'Biofilm, algae, shrimp pellets, blanched veggies.', socialNeeds: 'Peaceful; keep in colonies of 10+.', breedingInfo: 'Breeds readily in freshwater; females carry green eggs.', commonDiseases: 'Failed molts from soft or unstable water.', waterChangeNeeds: '10-15% weekly', stockingRecommendations: 'Colony of 10+ in a 5-10 gallon planted tank.', specialConsiderations: 'Do not mix with other Neocaridina colors — they interbreed.', tags: ['shrimp', 'neocaridina', 'colorful'] },
    { name: 'Vampire Shrimp', scientificName: 'Atya gabonensis', category: AnimalCategory.INVERTEBRATE, habitats: [Habitat.FRESHWATER], biome: Biome.RIVER, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 20, tempMin: 74, tempMax: 84, phMin: 6.5, phMax: 7.8, maxSize: 5, lifespan: '1-3 years', origin: 'West Africa', imageUrl: img('animal', 'Vampire Shrimp'), description: 'Large filter-feeding shrimp that fans the current for food.', careGuide: 'Mature tank, strong but gentle current, fine sand and rocks.', feedingGuide: 'Fine powdered foods, phytoplankton, natural biofilm and detritus.', socialNeeds: 'Peaceful; keep singly or in small groups.', breedingInfo: 'Requires brackish marine larval stage — not bred in fresh.', commonDiseases: 'Failed molts; sensitive to copper.', waterChangeNeeds: '20-25% weekly', stockingRecommendations: 'One or a small group in a 20+ gallon river tank.', specialConsiderations: 'Hides by day and feeds at night — provide current and cover.', tags: ['shrimp', 'filter-feeder', 'river'] },
    { name: 'Rabbit Snail', scientificName: 'Tylomelania spp.', category: AnimalCategory.INVERTEBRATE, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 10, tempMin: 76, tempMax: 88, phMin: 7, phMax: 8, maxSize: 3, lifespan: '1-3 years', origin: 'Sulawesi', imageUrl: img('animal', 'Rabbit Snail'), description: 'Long-snouted snail with a conical shell and panda-like colors.', careGuide: 'Warm, hard, alkaline water with sand substrate.', feedingGuide: 'Algae, sinking wafers, blanched veggies, detritus.', socialNeeds: 'Peaceful; can be kept singly or in groups.', breedingInfo: 'Live bearer — one baby at a time.', commonDiseases: 'Shell erosion in soft acidic water.', waterChangeNeeds: '10-20% weekly', stockingRecommendations: 'One or more per 10 gallons.', specialConsiderations: 'Burrows deep — ensure sand, not sharp gravel.', tags: ['snail', 'burrower', 'sulawesi'] },
    { name: 'Frogspawn Coral', scientificName: 'Euphyllia divisa', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.CARNIVORE, minTankSize: 30, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 6, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Frogspawn Coral'), description: 'Wall-form LPS coral with branching tentacles tipped in color.', careGuide: 'Moderate light and flow; leave room for sweeper tentacles.', feedingGuide: 'Photosynthetic; target feed mysis and reef roids weekly.', socialNeeds: 'Aggressive to nearby corals via long sweeper tentacles.', breedingInfo: 'Propagated by fragging heads.', commonDiseases: 'Tissue recession from poor flow or parameter swings.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Place with 6+ inches of clearance.', specialConsiderations: 'Sweeper tentacles can sting neighbors several inches away.', tags: ['coral', 'lps', 'euphyllia'] },
    { name: 'Torch Coral', scientificName: 'Euphyllia glabrescens', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.CARNIVORE, minTankSize: 30, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 8, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Torch Coral'), description: 'LPS coral with long, flowing tentacles that sway like a torch.', careGuide: 'Moderate light and flow; stable calcium and alkalinity.', feedingGuide: 'Photosynthetic; target feed mysis and reef roids.', socialNeeds: 'Aggressive to other Euphyllia via sweeper tentacles.', breedingInfo: 'Propagated by fragging branches.', commonDiseases: 'Brown jelly infection and tissue recession.', waterChangeNeeds: '10-20% biweekly', stockingRecommendations: 'Place with clearance for sweepers.', specialConsiderations: 'Different Euphyllia types can war — give space.', tags: ['coral', 'lps', 'euphyllia'] },
    { name: 'Birdsnest Coral', scientificName: 'Seriatopora hystrix', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.ADVANCED, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 30, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 8, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Birdsnest Coral'), description: 'Thin-branched SPS coral that grows into a dense nest shape.', careGuide: 'High light and strong, random flow; very stable parameters.', feedingGuide: 'Photosynthetic; benefits from amino acids and fine particulate foods.', socialNeeds: 'Peaceful but can be overgrown by aggressive corals.', breedingInfo: 'Fragged by cutting branches.', commonDiseases: 'Rapid tissue necrosis (RTN) from instability.', waterChangeNeeds: '10-20% weekly', stockingRecommendations: 'For mature, stable reef tanks only.', specialConsiderations: 'Demands rock-solid alkalinity and low nutrients.', tags: ['coral', 'sps', 'advanced'] },
    { name: 'Montipora Coral', scientificName: 'Montipora capricornis', category: AnimalCategory.CORAL, habitats: [Habitat.SALTWATER], biome: Biome.REEF, difficulty: Difficulty.INTERMEDIATE, temperament: Temperament.PEACEFUL, dietType: DietType.OMNIVORE, minTankSize: 30, tempMin: 75, tempMax: 80, phMin: 8.1, phMax: 8.4, maxSize: 10, lifespan: 'Indefinite', origin: 'Indo-Pacific', imageUrl: img('animal', 'Montipora Coral'), description: 'Plating SPS coral that forms whirling plate-like colonies.', careGuide: 'High light and moderate flow; stable calcium and alkalinity.', feedingGuide: 'Photosynthetic; occasional fine particulate feeding.', socialNeeds: 'Peaceful but shades anything beneath its plates.', breedingInfo: 'Fragged by chipping plates.', commonDiseases: 'Tissue loss from parameter swings or pests.', waterChangeNeeds: '10-20% weekly', stockingRecommendations: 'Place high in the rockwork with room to plate out.', specialConsiderations: 'Fast grower — plan for shading as it spreads.', tags: ['coral', 'sps', 'plating'] },
  ];

  const newPlants = [
    { name: 'Staurogyne Repens', scientificName: 'Staurogyne repens', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.INTERMEDIATE, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.SLOW, maxHeight: 4, placement: PlantPlacement.FOREGROUND, co2Required: false, tempMin: 68, tempMax: 82, phMin: 6, phMax: 7.5, imageUrl: img('plant', 'Staurogyne Repens'), description: 'Compact stem plant that forms a low bushy foreground carpet.', careGuide: 'Plant stems vertically and trim tops to encourage lateral growth.', propagation: 'Stem cuttings.', trimmingNeeds: 'Trim tops to maintain carpet.', nutrientNeeds: 'Moderate.', substrateNeeds: 'Nutrient-rich preferred.', co2Notes: 'Optional but helpful.', tags: ['foreground', 'carpet', 'bushy'] },
    { name: 'Ludwigia Super Red', scientificName: 'Ludwigia palustris', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.RIVER, difficulty: Difficulty.INTERMEDIATE, lightRequirement: LightLevel.HIGH, growthRate: GrowthRate.FAST, maxHeight: 12, placement: PlantPlacement.BACKGROUND, co2Required: false, tempMin: 68, tempMax: 82, phMin: 6, phMax: 7.5, imageUrl: img('plant', 'Ludwigia Super Red'), description: 'Intensely red stem plant under high light and iron.', careGuide: 'Provide high light and iron for best color.', propagation: 'Cuttings.', trimmingNeeds: 'Prune tops and replant.', nutrientNeeds: 'Moderate-high. Iron essential.', substrateNeeds: 'Any.', co2Notes: 'Optional but improves color.', tags: ['stem-plant', 'colorful', 'high-light'] },
    { name: 'Alternanthera Reineckii', scientificName: 'Alternanthera reineckii', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.ADVANCED, lightRequirement: LightLevel.HIGH, growthRate: GrowthRate.MODERATE, maxHeight: 12, placement: PlantPlacement.MIDGROUND, co2Required: false, tempMin: 70, tempMax: 80, phMin: 6, phMax: 7.5, imageUrl: img('plant', 'Alternanthera Reineckii'), description: 'Stunning red-leaf stem plant for highlight aquascapes.', careGuide: 'High light, iron, and CO2 recommended for vibrant red.', propagation: 'Cuttings.', trimmingNeeds: 'Trim tops; replant cuttings.', nutrientNeeds: 'High.', substrateNeeds: 'Nutrient-rich.', co2Notes: 'Recommended.', tags: ['stem-plant', 'red', 'advanced'] },
    { name: 'Utricularia Graminifolia', scientificName: 'Utricularia graminifolia', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.EXPERT, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.SLOW, maxHeight: 2, placement: PlantPlacement.FOREGROUND, co2Required: false, tempMin: 68, tempMax: 78, phMin: 5.5, phMax: 7, imageUrl: img('plant', 'Utricularia Graminifolia'), description: 'Carnivorous grass-like carpet that traps micro-organisms.', careGuide: 'Clean water, moderate light, no algae competition.', propagation: 'Spreads as a mat.', trimmingNeeds: 'Trim to contain spread.', nutrientNeeds: 'Very low.', substrateNeeds: 'Nutrient-poor inert substrate.', co2Notes: 'Optional.', tags: ['carpet', 'carnivorous', 'expert'] },
    { name: 'Begonia', scientificName: 'Begonia spp.', category: PlantCategory.TERRESTRIAL, habitats: [Habitat.VIVARIUM, Habitat.TERRARIUM], biome: Biome.TROPICAL_RAINFOREST, difficulty: Difficulty.BEGINNER, lightRequirement: LightLevel.LOW, growthRate: GrowthRate.MODERATE, maxHeight: 8, placement: PlantPlacement.MIDGROUND, co2Required: false, tempMin: 65, tempMax: 80, phMin: 5.5, phMax: 7, imageUrl: img('plant', 'Begonia'), description: 'Colorful terrestrial plant with many compact varieties for vivariums.', careGuide: 'High humidity, moist but not soggy substrate, indirect light.', propagation: 'Leaf or stem cuttings.', trimmingNeeds: 'Remove old leaves and flowers.', nutrientNeeds: 'Low.', substrateNeeds: 'Well-draining humus mix.', co2Notes: 'Atmospheric.', tags: ['vivarium', 'colorful', 'terrestrial'] },
    { name: 'Tillandsia Ionantha', scientificName: 'Tillandsia ionantha', category: PlantCategory.EPIPHYTE, habitats: [Habitat.VIVARIUM, Habitat.TERRARIUM], biome: Biome.TROPICAL_RAINFOREST, difficulty: Difficulty.BEGINNER, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.SLOW, maxHeight: 3, placement: PlantPlacement.ATTACHED, co2Required: false, tempMin: 60, tempMax: 85, phMin: 5.5, phMax: 7.5, imageUrl: img('plant', 'Tillandsia Ionantha'), description: 'Small air plant that absorbs moisture through leaves; turns red when blooming.', careGuide: 'Mist 2-3 times weekly or soak weekly; provide bright indirect light.', propagation: 'Pups form at base.', trimmingNeeds: 'Remove dead leaves.', nutrientNeeds: 'Low.', substrateNeeds: 'None.', co2Notes: 'Atmospheric.', tags: ['vivarium', 'air-plant', 'epiphyte'] },
    { name: 'Pearl Weed', scientificName: 'Micranthemum micranthemoides', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.MODERATE, maxHeight: 4, placement: PlantPlacement.FOREGROUND, co2Required: false, tempMin: 64, tempMax: 82, phMin: 5, phMax: 7.5, imageUrl: img('plant', 'Pearl Weed'), description: 'Tiny round leaves on creeping stems that form a bright green cushion.', careGuide: 'Plant in small clumps; trim short to encourage lateral spread.', propagation: 'Stem cuttings.', trimmingNeeds: 'Trim frequently to keep a low carpet.', nutrientNeeds: 'Moderate.', substrateNeeds: 'Nutrient-rich preferred.', co2Notes: 'Optional; speeds growth.', tags: ['foreground', 'carpet', 'beginner'] },
    { name: 'Hydrocotyle Tripartita', scientificName: 'Hydrocotyle tripartita', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.INTERMEDIATE, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.FAST, maxHeight: 4, placement: PlantPlacement.FOREGROUND, co2Required: false, tempMin: 64, tempMax: 82, phMin: 5, phMax: 7.5, imageUrl: img('plant', 'Hydrocotyle Tripartita'), description: 'Japanese pennywort with clover-like leaves that creeps across the substrate.', careGuide: 'Tuck runners into the substrate; prune to direct spread.', propagation: 'Runner cuttings.', trimmingNeeds: 'Trim runaway runners to contain spread.', nutrientNeeds: 'Moderate.', substrateNeeds: 'Nutrient-rich preferred.', co2Notes: 'Optional but improves form.', tags: ['foreground', 'carpet', 'runner'] },
    { name: 'Cryptocoryne Parva', scientificName: 'Cryptocoryne parva', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.BEGINNER, lightRequirement: LightLevel.LOW, growthRate: GrowthRate.SLOW, maxHeight: 2, placement: PlantPlacement.FOREGROUND, co2Required: false, tempMin: 72, tempMax: 82, phMin: 5.5, phMax: 7.5, imageUrl: img('plant', 'Cryptocoryne Parva'), description: 'Smallest crypt — a slow, low rosette for the foreground.', careGuide: 'Patience required; dislikes being moved.', propagation: 'Runners.', trimmingNeeds: 'Remove old leaves.', nutrientNeeds: 'Low-moderate.', substrateNeeds: 'Nutrient-rich preferred.', co2Notes: 'Not needed.', tags: ['foreground', 'low-light', 'crypt'] },
    { name: 'Blyxa Japonica', scientificName: 'Blyxa japonica', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.INTERMEDIATE, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.MODERATE, maxHeight: 6, placement: PlantPlacement.MIDGROUND, co2Required: false, tempMin: 68, tempMax: 82, phMin: 5.5, phMax: 7.5, imageUrl: img('plant', 'Blyxa Japonica'), description: 'Grassy rosette that forms a golden-green tuft midground.', careGuide: 'Soft, clean water; high light brings golden color.', propagation: 'Side shoots and division.', trimmingNeeds: 'Thin outer leaves.', nutrientNeeds: 'Moderate.', substrateNeeds: 'Nutrient-rich.', co2Notes: 'Recommended for lush growth.', tags: ['midground', 'grassy', 'rosette'] },
    { name: 'Pogostemon Helferi', scientificName: 'Pogostemon helferi', category: PlantCategory.AQUATIC, habitats: [Habitat.FRESHWATER], biome: Biome.STREAM, difficulty: Difficulty.INTERMEDIATE, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.SLOW, maxHeight: 3, placement: PlantPlacement.FOREGROUND, co2Required: false, tempMin: 72, tempMax: 82, phMin: 5.5, phMax: 7.5, imageUrl: img('plant', 'Pogostemon Helferi'), description: 'Distinctive curly green rosette also called Downoi or little star.', careGuide: 'Stable water; plant in groups for a starry foreground.', propagation: 'Side shoots.', trimmingNeeds: 'Remove old leaves.', nutrientNeeds: 'Moderate.', substrateNeeds: 'Nutrient-rich.', co2Notes: 'Recommended.', tags: ['foreground', 'rosette', 'curly'] },
    { name: 'Selaginella', scientificName: 'Selaginella spp.', category: PlantCategory.MOSS, habitats: [Habitat.VIVARIUM, Habitat.TERRARIUM], biome: Biome.CLOUD_FOREST, difficulty: Difficulty.BEGINNER, lightRequirement: LightLevel.LOW, growthRate: GrowthRate.SLOW, maxHeight: 4, placement: PlantPlacement.FOREGROUND, co2Required: false, tempMin: 60, tempMax: 80, phMin: 5.5, phMax: 7, imageUrl: img('plant', 'Selaginella'), description: 'Spikemoss that carpets humid vivarium floors with feathery fronds.', careGuide: 'Constant high humidity, moist substrate, low to medium light.', propagation: 'Stem cuttings and creeping spread.', trimmingNeeds: 'Trim edges to contain spread.', nutrientNeeds: 'Low.', substrateNeeds: 'Moist humus mix.', co2Notes: 'Atmospheric.', tags: ['vivarium', 'carpet', 'humidity'] },
    { name: 'Cryptanthus', scientificName: 'Cryptanthus spp.', category: PlantCategory.TERRESTRIAL, habitats: [Habitat.VIVARIUM, Habitat.TERRARIUM], biome: Biome.TROPICAL_RAINFOREST, difficulty: Difficulty.BEGINNER, lightRequirement: LightLevel.MEDIUM, growthRate: GrowthRate.SLOW, maxHeight: 6, placement: PlantPlacement.MIDGROUND, co2Required: false, tempMin: 60, tempMax: 85, phMin: 5.5, phMax: 7, imageUrl: img('plant', 'Cryptanthus'), description: 'Earth stars — terrestrial bromeliads with pink-striped starry leaves.', careGuide: 'Humid, well-draining substrate; bright indirect light.', propagation: 'Pups at the base.', trimmingNeeds: 'Remove spent leaves.', nutrientNeeds: 'Low.', substrateNeeds: 'Well-draining humus mix.', co2Notes: 'Atmospheric.', tags: ['vivarium', 'bromeliad', 'colorful'] },
  ];

  const newProducts = [
    { name: 'Tetra Whisper AP300', brand: 'Tetra', category: ProductCategory.AIR_PUMP, description: 'Powerful air pump for deep tanks and multiple sponge filters.', imageUrl: img('product', 'Tetra Whisper AP300'), priceRange: PriceRange.MID_RANGE, rating: 4.4, tags: ['air-pump', 'powerful', 'sponge-filter'] },
    { name: 'USB Nano Air Pump', brand: 'Generic', category: ProductCategory.AIR_PUMP, description: 'Tiny portable USB-powered air pump for nano tanks and travel.', imageUrl: img('product', 'USB Nano Air Pump'), priceRange: PriceRange.BUDGET, rating: 4.0, tags: ['air-pump', 'nano', 'usb'] },
    { name: 'Silicone Airline Tubing', brand: 'Generic', category: ProductCategory.HOSE_TUBING, description: 'Flexible clear silicone tubing for air pumps and small filters.', imageUrl: img('product', 'Silicone Airline Tubing'), priceRange: PriceRange.BUDGET, rating: 4.6, tags: ['hose', 'airline', 'silicone'] },
    { name: 'PVC Braided Tubing', brand: 'Generic', category: ProductCategory.HOSE_TUBING, description: 'Reinforced tubing for canister filters and water changers.', imageUrl: img('product', 'PVC Braided Tubing'), priceRange: PriceRange.MID_RANGE, rating: 4.5, tags: ['hose', 'reinforced', 'filter'] },
    { name: 'Repashy Calcium Plus', brand: 'Repashy', category: ProductCategory.SUPPLEMENT, description: 'All-in-one calcium and vitamin supplement for reptiles and amphibians.', imageUrl: img('product', 'Repashy Calcium Plus'), priceRange: PriceRange.MID_RANGE, rating: 4.7, tags: ['supplement', 'calcium', 'reptile', 'amphibian'] },
    { name: 'Zoo Med Reptivite', brand: 'Zoo Med', category: ProductCategory.SUPPLEMENT, description: 'Complete multivitamin powder for reptiles.', imageUrl: img('product', 'Zoo Med Reptivite'), priceRange: PriceRange.BUDGET, rating: 4.4, tags: ['supplement', 'multivitamin', 'reptile'] },
    { name: 'Lava Rock', brand: 'Generic', category: ProductCategory.HARDSCAPE, description: 'Porous volcanic rock that provides surface area for beneficial bacteria.', imageUrl: img('product', 'Lava Rock'), priceRange: PriceRange.BUDGET, rating: 4.5, tags: ['hardscape', 'porous', 'biological-media'] },
    { name: 'Slate Stone', brand: 'Generic', category: ProductCategory.HARDSCAPE, description: 'Flat sedimentary stone useful for caves, basking, and aquascaping.', imageUrl: img('product', 'Slate Stone'), priceRange: PriceRange.BUDGET, rating: 4.3, tags: ['hardscape', 'stone', 'caves'] },
    { name: 'Seachem Tidal 110 HOB Filter', brand: 'Seachem', category: ProductCategory.FILTER, description: 'Large hang-on-back filter with a surface skimmer and adjustable flow.', imageUrl: img('product', 'Seachem Tidal 110 HOB Filter'), priceRange: PriceRange.MID_RANGE, rating: 4.7, tags: ['filter', 'hob', 'surface-skimmer'] },
    { name: 'Kessil A360X Tuna Blue', brand: 'Kessil', category: ProductCategory.LIGHTING, description: 'Premium pendant reef light with dense blue spectrum and shimmer effect.', imageUrl: img('product', 'Kessil A360X Tuna Blue'), priceRange: PriceRange.PREMIUM, rating: 4.8, tags: ['lighting', 'reef', 'led'] },
    { name: 'Ecotech Marine VorTech MP40 Wavemaker', brand: 'Ecotech Marine', category: ProductCategory.OTHER, description: 'Wireless propeller pump that creates randomized reef-style flow.', imageUrl: img('product', 'Ecotech Marine VorTech MP40 Wavemaker'), priceRange: PriceRange.PREMIUM, rating: 4.8, tags: ['wavemaker', 'flow', 'reef'] },
    { name: 'Aquaforest Reef Salt', brand: 'Aquaforest', category: ProductCategory.WATER_TREATMENT, description: 'Synthetic reef salt mix balanced for calcium and alkalinity at natural levels.', imageUrl: img('product', 'Aquaforest Reef Salt'), priceRange: PriceRange.MID_RANGE, rating: 4.6, tags: ['salt-mix', 'reef', 'marine'] },
    { name: 'Inkbird ITC-308 Temperature Controller', brand: 'Inkbird', category: ProductCategory.TOOL, description: 'Dual-relay thermostat that independently controls a heater and chiller.', imageUrl: img('product', 'Inkbird ITC-308 Temperature Controller'), priceRange: PriceRange.BUDGET, rating: 4.5, tags: ['controller', 'temperature', 'safety'] },
    { name: 'Coral Rx Coral Dip', brand: 'Coral Rx', category: ProductCategory.WATER_TREATMENT, description: 'Iodine-free coral dip for treating new arrivals before introducing to a reef.', imageUrl: img('product', 'Coral Rx Coral Dip'), priceRange: PriceRange.BUDGET, rating: 4.6, tags: ['coral-dip', 'quarantine', 'reef'] },
    { name: 'Seachem Matrix Bio Media', brand: 'Seachem', category: ProductCategory.FILTER, description: 'Porous rock bio-media offering massive surface area for nitrifying bacteria.', imageUrl: img('product', 'Seachem Matrix Bio Media'), priceRange: PriceRange.BUDGET, rating: 4.7, tags: ['bio-media', 'filter-media', 'nitrification'] },
    { name: 'BRS 6-Stage RO/DI System', brand: 'Bulk Reef Supply', category: ProductCategory.WATER_TREATMENT, description: 'Benchtop reverse osmosis and deionization system for zero-TDS mixing water.', imageUrl: img('product', 'BRS 6-Stage RO/DI System'), priceRange: PriceRange.MID_RANGE, rating: 4.8, tags: ['ro-di', 'water', 'reef'] },
  ];

  const compatPairs: [string, string, CompatibilityLevel, string][] = [
    ['Clownfish', 'Royal Gramma', CompatibilityLevel.COMPATIBLE, 'Both are small, reef-safe, and occupy different niches.'],
    ['Clownfish', 'Firefish Goby', CompatibilityLevel.COMPATIBLE, 'Peaceful reef fish that ignore each other.'],
    ['Royal Gramma', 'Firefish Goby', CompatibilityLevel.COMPATIBLE, 'Two small peaceful reef fish that prefer different hiding spots.'],
    ['Clownfish', 'Yellow Tang', CompatibilityLevel.CAUTION, 'Both can be semi-aggressive; monitor in smaller tanks.'],
    ['Zoanthids', 'Mushroom Coral', CompatibilityLevel.COMPATIBLE, 'Both are forgiving soft corals that tolerate similar conditions.'],
    ['Hammer Coral', 'Zoanthids', CompatibilityLevel.CAUTION, 'Keep space for hammer coral sweeper tentacles.'],
    ['Electric Blue Ram', 'Neon Tetra', CompatibilityLevel.COMPATIBLE, 'Both appreciate warm, soft water and peaceful communities.'],
    ['Peacock Cichlid', 'Neon Tetra', CompatibilityLevel.INCOMPATIBLE, 'Very different water parameters and peacocks may eat neons.'],
    ['Peacock Cichlid', 'Corydoras Catfish', CompatibilityLevel.INCOMPATIBLE, 'Corydoras need cooler, softer water than African cichlids.'],
    ['Altum Angelfish', 'Cardinal Tetra', CompatibilityLevel.CAUTION, 'Cardinals tolerate discus/altum temps but may be eaten as adults grow.'],
    ['Tiger Barb', 'Pearl Gourami', CompatibilityLevel.CAUTION, 'Tiger barbs may nip the long fins of pearl gouramis.'],
    ['Lawnmower Blenny', 'Clownfish', CompatibilityLevel.COMPATIBLE, 'Peaceful herbivore that ignores clownfish.'],
    ['Ember Tetra', 'Neon Tetra', CompatibilityLevel.COMPATIBLE, 'Both are small, peaceful schoolers that appreciate similar soft, acidic water.'],
    ['Ember Tetra', 'Betta Fish', CompatibilityLevel.CAUTION, 'Ember tetras can nip betta fins; use a large planted tank and watch closely.'],
    ['Rummynose Tetra', 'Neon Tetra', CompatibilityLevel.COMPATIBLE, 'Two peaceful schooling tetras that coexist in planted community tanks.'],
    ['Rummynose Tetra', 'Cardinal Tetra', CompatibilityLevel.COMPATIBLE, 'Peaceful schoolers; keep in groups of 6+ each.'],
    ['Celestial Pearl Danio', 'Chili Rasbora', CompatibilityLevel.COMPATIBLE, 'Two tiny, peaceful nano fish ideal for species-rich nano tanks.'],
    ['Chili Rasbora', 'Betta Fish', CompatibilityLevel.COMPATIBLE, 'Tiny, peaceful rasbora that shares warm, soft, acidic blackwater with bettas.'],
    ['Siamese Algae Eater', 'Tiger Barb', CompatibilityLevel.COMPATIBLE, 'True SAEs are peaceful; avoid the aggressive Chinese algae eater lookalike.'],
    ['Honey Gourami', 'Pearl Gourami', CompatibilityLevel.CAUTION, 'Both gouramis; provide space and hiding spots to limit territorial chasing.'],
    ['Honey Gourami', 'Neon Tetra', CompatibilityLevel.COMPATIBLE, 'Peaceful dwarf gourami pairs well with small schooling tetras.'],
    ['Panda Cory', 'Corydoras Catfish', CompatibilityLevel.COMPATIBLE, 'Different Corydoras species that shoal peacefully over soft substrate.'],
    ['Panda Cory', 'Ember Tetra', CompatibilityLevel.COMPATIBLE, 'Peaceful bottom dweller with a midwater schooler; no overlap in niche.'],
    ['Clown Pleco', 'Bristlenose Pleco', CompatibilityLevel.COMPATIBLE, 'Two plecos need separate hides and driftwood but coexist in 30+ gallons.'],
    ['Blue Velvet Shrimp', 'Cherry Shrimp', CompatibilityLevel.CAUTION, 'Same genus (Neocaridina); will interbreed and produce brown wild-type offspring.'],
    ['Blue Velvet Shrimp', 'Betta Fish', CompatibilityLevel.CAUTION, 'Bettas may hunt small shrimp; provide dense moss cover.'],
    ['Vampire Shrimp', 'Bamboo Shrimp', CompatibilityLevel.COMPATIBLE, 'Two filter-feeding shrimp that coexist in moderate current.'],
    ['Rabbit Snail', 'Nerite Snail', CompatibilityLevel.COMPATIBLE, 'Peaceful snails occupying the substrate and glass without conflict.'],
    ['Frogspawn Coral', 'Hammer Coral', CompatibilityLevel.CAUTION, 'Both Euphyllia LPS; give space — sweeper tentacles can sting neighbors.'],
    ['Torch Coral', 'Hammer Coral', CompatibilityLevel.CAUTION, 'Different Euphyllia types can war via sweeper tentacles; keep apart.'],
    ['Birdsnest Coral', 'Montipora Coral', CompatibilityLevel.COMPATIBLE, 'Two peaceful SPS corals that thrive under similar high light and flow.'],
    ['Birdsnest Coral', 'Hammer Coral', CompatibilityLevel.CAUTION, 'LPS sweeper tentacles can damage delicate SPS branches; keep distance.'],
  ];

  let animalCount = 0;
  for (const data of newAnimals) {
    const existing = await prisma.animal.findFirst({ where: { name: data.name } });
    if (!existing) {
      await prisma.animal.create({ data });
      animalCount++;
    }
  }

  let plantCount = 0;
  for (const data of newPlants) {
    const existing = await prisma.plant.findFirst({ where: { name: data.name } });
    if (!existing) {
      await prisma.plant.create({ data });
      plantCount++;
    }
  }

  let productCount = 0;
  for (const data of newProducts) {
    const existing = await prisma.product.findFirst({ where: { name: data.name } });
    if (!existing) {
      await prisma.product.create({ data });
      productCount++;
    }
  }

  let compatCount = 0;
  for (const [aName, bName, level, notes] of compatPairs) {
    const animalA = await prisma.animal.findFirst({ where: { name: aName } });
    const animalB = await prisma.animal.findFirst({ where: { name: bName } });
    if (!animalA || !animalB) {
      console.warn(`Skipping compat rule: missing ${aName} or ${bName}`);
      continue;
    }
    const existing = await prisma.animalCompatibility.findFirst({
      where: {
        OR: [
          { animalAId: animalA.id, animalBId: animalB.id },
          { animalAId: animalB.id, animalBId: animalA.id },
        ],
      },
    });
    if (!existing) {
      await prisma.animalCompatibility.create({
        data: { animalAId: animalA.id, animalBId: animalB.id, level, notes },
      });
      compatCount++;
    }
  }

  console.log(`Added ${animalCount} animals, ${plantCount} plants, ${productCount} products, ${compatCount} compat rules.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
