import { PrismaClient, Difficulty, AnimalCategory, Temperament, DietType, PlantCategory, LightLevel, GrowthRate, PlantPlacement, ProductCategory, PriceRange, CompatibilityLevel } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding Aquascape database with verified data...');

  const animals = await Promise.all([
    prisma.animal.create({
      data: {
        name: 'Neon Tetra',
        scientificName: 'Paracheirodon innesi',
        category: AnimalCategory.FISH,
        difficulty: Difficulty.BEGINNER,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.OMNIVORE,
        minTankSize: 10,
        tempMin: 68,
        tempMax: 79,
        phMin: 6.0,
        phMax: 7.0,
        maxSize: 1.5,
        lifespan: '5-8 years',
        origin: 'South America (Amazon Basin)',
        description: 'Small, vibrant schooling fish with iridescent blue and red coloration. Must be kept in groups of 6 or more. Peaceful community fish ideal for planted tanks.',
        tags: ['schooling', 'colorful', 'small', 'community', 'planted-tank', 'amazon'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Betta Fish',
        scientificName: 'Betta splendens',
        category: AnimalCategory.FISH,
        difficulty: Difficulty.BEGINNER,
        temperament: Temperament.SEMI_AGGRESSIVE,
        dietType: DietType.CARNIVORE,
        minTankSize: 5,
        tempMin: 76,
        tempMax: 82,
        phMin: 6.5,
        phMax: 7.5,
        maxSize: 3,
        lifespan: '3-5 years',
        origin: 'Southeast Asia (Thailand, Cambodia, Vietnam)',
        description: 'Stunning solitary fish with flowing fins and vibrant colors. Males are highly territorial and must be kept alone. Labyrinth organ allows them to breathe atmospheric air. Prefer calm water with minimal flow.',
        tags: ['solo', 'colorful', 'labyrinth', 'beginner-friendly', 'low-flow'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Corydoras Catfish',
        scientificName: 'Corydoras paleatus',
        category: AnimalCategory.FISH,
        difficulty: Difficulty.BEGINNER,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.OMNIVORE,
        minTankSize: 20,
        tempMin: 72,
        tempMax: 79,
        phMin: 6.0,
        phMax: 7.5,
        maxSize: 2.5,
        lifespan: '5-7 years',
        origin: 'South America',
        description: 'Bottom-dwelling catfish that help keep substrate clean by sifting for food. Must be kept in groups of 4 or more. Use sand or smooth gravel substrate to protect delicate barbels. Excellent community tank mates.',
        tags: ['bottom-dweller', 'cleaner', 'schooling', 'peaceful', 'community'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Cherry Shrimp',
        scientificName: 'Neocaridina davidi',
        category: AnimalCategory.INVERTEBRATE,
        difficulty: Difficulty.BEGINNER,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.OMNIVORE,
        minTankSize: 5,
        tempMin: 65,
        tempMax: 80,
        phMin: 6.5,
        phMax: 8.0,
        maxSize: 1.5,
        lifespan: '1-2 years',
        origin: 'Taiwan',
        description: 'Hardy, colorful dwarf shrimp excellent for planted tanks and algae control. Breed readily in stable conditions. Provide hiding spots for young. Avoid copper-based medications. Sensitive to ammonia spikes.',
        tags: ['algae-eater', 'colorful', 'small', 'invertebrate', 'breeder', 'planted-tank'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Angelfish',
        scientificName: 'Pterophyllum scalare',
        category: AnimalCategory.FISH,
        difficulty: Difficulty.INTERMEDIATE,
        temperament: Temperament.SEMI_AGGRESSIVE,
        dietType: DietType.OMNIVORE,
        minTankSize: 30,
        tempMin: 76,
        tempMax: 84,
        phMin: 6.0,
        phMax: 7.5,
        maxSize: 6,
        lifespan: '10-12 years',
        origin: 'South America (Amazon Basin)',
        description: 'Elegant cichlid with tall, disc-shaped body and trailing fins. Can be territorial, especially when breeding. May eat very small fish. Requires tall tanks (minimum 18" height). Best kept in pairs or small groups.',
        tags: ['centerpiece', 'tall', 'semi-aggressive', 'cichlid', 'amazon'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Discus',
        scientificName: 'Symphysodon',
        category: AnimalCategory.FISH,
        difficulty: Difficulty.EXPERT,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.OMNIVORE,
        minTankSize: 55,
        tempMin: 82,
        tempMax: 88,
        phMin: 6.0,
        phMax: 7.0,
        maxSize: 8,
        lifespan: '10-15 years',
        origin: 'South America (Amazon Basin)',
        description: 'The "king of the aquarium." Requires pristine water conditions with frequent water changes (25-50% weekly). Sensitive to water quality fluctuations. Best kept in groups of 5+ in species-only or carefully selected community tanks. Demands experienced care.',
        tags: ['centerpiece', 'advanced', 'colorful', 'sensitive', 'high-maintenance', 'amazon'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Amano Shrimp',
        scientificName: 'Caridina multidentata',
        category: AnimalCategory.INVERTEBRATE,
        difficulty: Difficulty.BEGINNER,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.HERBIVORE,
        minTankSize: 10,
        tempMin: 70,
        tempMax: 80,
        phMin: 6.5,
        phMax: 7.5,
        maxSize: 2,
        lifespan: '2-3 years',
        origin: 'Japan, Taiwan',
        description: 'Excellent algae eaters, larger and hardier than cherry shrimp. Will not breed in freshwater (larvae require brackish water). Very effective at controlling hair algae and other soft algae types.',
        tags: ['algae-eater', 'hardy', 'invertebrate', 'cleaner', 'non-breeding'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Leopard Gecko',
        scientificName: 'Eublepharis macularius',
        category: AnimalCategory.REPTILE,
        difficulty: Difficulty.BEGINNER,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.CARNIVORE,
        minTankSize: 20,
        tempMin: 75,
        tempMax: 90,
        maxSize: 10,
        lifespan: '15-20 years',
        origin: 'South Asia (Pakistan, India, Afghanistan)',
        description: 'Docile, easy-to-handle lizard perfect for beginners. Nocturnal and terrestrial. Requires temperature gradient (cool side 75-80°F, warm side 85-90°F). Feed insects dusted with calcium and vitamin D3. Provide moist hide for shedding.',
        tags: ['terrestrial', 'nocturnal', 'handleable', 'vivarium', 'desert'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Cardinal Tetra',
        scientificName: 'Paracheirodon axelrodi',
        category: AnimalCategory.FISH,
        difficulty: Difficulty.INTERMEDIATE,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.OMNIVORE,
        minTankSize: 20,
        tempMin: 73,
        tempMax: 81,
        phMin: 5.5,
        phMax: 7.0,
        maxSize: 2,
        lifespan: '4-5 years',
        origin: 'South America (Orinoco and Rio Negro)',
        description: 'Similar to neon tetra but with red extending full body length. More sensitive to water conditions than neons. Must be kept in schools of 8+. Prefers soft, acidic water with dim lighting and plenty of plants.',
        tags: ['schooling', 'colorful', 'sensitive', 'community', 'blackwater'],
      },
    }),
    prisma.animal.create({
      data: {
        name: 'Bristlenose Pleco',
        scientificName: 'Ancistrus sp.',
        category: AnimalCategory.FISH,
        difficulty: Difficulty.BEGINNER,
        temperament: Temperament.PEACEFUL,
        dietType: DietType.HERBIVORE,
        minTankSize: 20,
        tempMin: 72,
        tempMax: 82,
        phMin: 6.5,
        phMax: 7.5,
        maxSize: 5,
        lifespan: '10-15 years',
        origin: 'South America',
        description: 'Excellent algae eater that stays smaller than common plecos. Peaceful bottom dweller. Provide driftwood for grazing and hiding spots. Supplement diet with algae wafers and blanched vegetables. Males develop distinctive bristly head growth.',
        tags: ['algae-eater', 'bottom-dweller', 'peaceful', 'driftwood', 'community'],
      },
    }),
  ]);

  const plants = await Promise.all([
    prisma.plant.create({
      data: {
        name: 'Java Fern',
        scientificName: 'Microsorum pteropus',
        category: PlantCategory.AQUATIC,
        difficulty: Difficulty.BEGINNER,
        lightRequirement: LightLevel.LOW,
        growthRate: GrowthRate.SLOW,
        maxHeight: 14,
        placement: PlantPlacement.ATTACHED,
        co2Required: false,
        tempMin: 68,
        tempMax: 82,
        phMin: 6.0,
        phMax: 7.5,
        description: 'Extremely hardy epiphytic plant that attaches to driftwood and rocks. Do not bury the rhizome in substrate (will rot). Thrives in low light and low-tech setups. Propagate by dividing rhizome or from plantlets on leaf undersides.',
        tags: ['low-light', 'attached', 'hardy', 'beginner', 'epiphyte', 'rhizome'],
      },
    }),
    prisma.plant.create({
      data: {
        name: 'Anubias Nana',
        scientificName: 'Anubias barteri var. nana',
        category: PlantCategory.AQUATIC,
        difficulty: Difficulty.BEGINNER,
        lightRequirement: LightLevel.LOW,
        growthRate: GrowthRate.SLOW,
        maxHeight: 6,
        placement: PlantPlacement.ATTACHED,
        co2Required: false,
        tempMin: 72,
        tempMax: 82,
        phMin: 6.0,
        phMax: 7.5,
        description: 'Compact, extremely hardy epiphytic plant perfect for attaching to hardscape. Do not bury rhizome. Very low maintenance and resistant to herbivorous fish. Slow grower but nearly indestructible. Propagate by rhizome division.',
        tags: ['low-light', 'compact', 'attached', 'beginner', 'epiphyte', 'indestructible'],
      },
    }),
    prisma.plant.create({
      data: {
        name: 'Amazon Sword',
        scientificName: 'Echinodorus amazonicus',
        category: PlantCategory.AQUATIC,
        difficulty: Difficulty.BEGINNER,
        lightRequirement: LightLevel.MEDIUM,
        growthRate: GrowthRate.MODERATE,
        maxHeight: 20,
        placement: PlantPlacement.BACKGROUND,
        co2Required: false,
        tempMin: 72,
        tempMax: 82,
        phMin: 6.5,
        phMax: 7.5,
        description: 'Classic background plant with broad, sword-shaped leaves. Heavy root feeder - use nutrient-rich substrate or root tabs. Can grow emersed. Excellent for beginners. May develop iron deficiency (yellow leaves) without adequate nutrients.',
        tags: ['background', 'broad-leaf', 'rooted', 'beginner', 'root-feeder'],
      },
    }),
    prisma.plant.create({
      data: {
        name: 'Java Moss',
        scientificName: 'Taxiphyllum barbieri',
        category: PlantCategory.MOSS,
        difficulty: Difficulty.BEGINNER,
        lightRequirement: LightLevel.LOW,
        growthRate: GrowthRate.MODERATE,
        maxHeight: 4,
        placement: PlantPlacement.ATTACHED,
        co2Required: false,
        tempMin: 59,
        tempMax: 86,
        phMin: 5.0,
        phMax: 8.0,
        description: 'Versatile moss that attaches to any surface. Excellent for shrimp breeding tanks (provides cover and biofilm). Tolerates wide parameter range. Can be trimmed and shaped. May collect debris - rinse during water changes.',
        tags: ['moss', 'shrimp-friendly', 'low-light', 'versatile', 'breeding', 'biofilm'],
      },
    }),
    prisma.plant.create({
      data: {
        name: 'Dwarf Hairgrass',
        scientificName: 'Eleocharis parvula',
        category: PlantCategory.AQUATIC,
        difficulty: Difficulty.INTERMEDIATE,
        lightRequirement: LightLevel.HIGH,
        growthRate: GrowthRate.MODERATE,
        maxHeight: 4,
        placement: PlantPlacement.FOREGROUND,
        co2Required: true,
        tempMin: 68,
        tempMax: 82,
        phMin: 6.0,
        phMax: 7.5,
        description: 'Creates beautiful carpet effect when grown in high light with CO2 injection. Plant in small clumps 1" apart in nutrient-rich substrate. Trim regularly to encourage horizontal growth. Challenging without CO2 and adequate lighting.',
        tags: ['carpet', 'high-light', 'co2', 'foreground', 'high-tech', 'carpeting'],
      },
    }),
    prisma.plant.create({
      data: {
        name: 'Pothos',
        scientificName: 'Epipremnum aureum',
        category: PlantCategory.TERRESTRIAL,
        difficulty: Difficulty.BEGINNER,
        lightRequirement: LightLevel.LOW,
        growthRate: GrowthRate.FAST,
        maxHeight: 72,
        placement: PlantPlacement.BACKGROUND,
        co2Required: false,
        tempMin: 65,
        tempMax: 85,
        phMin: 6.0,
        phMax: 7.5,
        description: 'Excellent for paludariums, ripariums, and hang-on-back filters. Roots grow in water while leaves stay emersed. Extremely effective at removing nitrates. Fast-growing vine that can be trained or trimmed. Toxic if ingested by pets.',
        tags: ['terrestrial', 'fast-growing', 'paludarium', 'air-purifying', 'nitrate-remover', 'emersed'],
      },
    }),
    prisma.plant.create({
      data: {
        name: 'Cryptocoryne Wendtii',
        scientificName: 'Cryptocoryne wendtii',
        category: PlantCategory.AQUATIC,
        difficulty: Difficulty.BEGINNER,
        lightRequirement: LightLevel.LOW,
        growthRate: GrowthRate.SLOW,
        maxHeight: 12,
        placement: PlantPlacement.MIDGROUND,
        co2Required: false,
        tempMin: 72,
        tempMax: 82,
        phMin: 6.0,
        phMax: 8.0,
        description: 'Hardy midground plant available in green, brown, and red varieties. May experience "crypt melt" when first planted (leaves die back then regrow). Do not move once established. Excellent for low-tech setups.',
        tags: ['midground', 'low-light', 'hardy', 'crypt-melt', 'root-feeder'],
      },
    }),
    prisma.plant.create({
      data: {
        name: 'Water Wisteria',
        scientificName: 'Hygrophila difformis',
        category: PlantCategory.AQUATIC,
        difficulty: Difficulty.BEGINNER,
        lightRequirement: LightLevel.MEDIUM,
        growthRate: GrowthRate.FAST,
        maxHeight: 20,
        placement: PlantPlacement.BACKGROUND,
        co2Required: false,
        tempMin: 72,
        tempMax: 82,
        phMin: 6.5,
        phMax: 7.5,
        description: 'Fast-growing stem plant that helps control algae by absorbing excess nutrients. Can be planted in substrate or left floating. Propagate by cutting and replanting tops. Leaf shape varies with light intensity.',
        tags: ['fast-growing', 'nutrient-absorber', 'beginner', 'stem-plant', 'algae-control'],
      },
    }),
  ]);

  await Promise.all([
    prisma.product.create({
      data: {
        name: 'Fluval 407 Canister Filter',
        brand: 'Fluval',
        category: ProductCategory.FILTER,
        priceRange: PriceRange.MID_RANGE,
        rating: 4.7,
        description: 'Reliable canister filter for tanks 50-100 gallons. Flow rate: 383 GPH. Quiet operation with multi-stage filtration. Includes spray bar for even water distribution.',
        tags: ['canister', 'large-tank', 'quiet', 'multi-stage'],
      },
    }),
    prisma.product.create({
      data: {
        name: 'Eheim Jager Aquarium Heater',
        brand: 'Eheim',
        category: ProductCategory.HEATER,
        priceRange: PriceRange.MID_RANGE,
        rating: 4.5,
        description: 'Precise, reliable submersible heater with shatterproof glass and thermal safety shutoff. Available in 25W-300W. Calibrated for accuracy within ±0.5°F. Made in Germany.',
        tags: ['submersible', 'precise', 'reliable', 'safety-shutoff'],
      },
    }),
    prisma.product.create({
      data: {
        name: 'Fluval Plant 3.0 LED',
        brand: 'Fluval',
        category: ProductCategory.LIGHTING,
        priceRange: PriceRange.PREMIUM,
        rating: 4.6,
        description: 'Full spectrum LED light with Bluetooth app control and programmable schedules. 120-degree light dispersion. Suitable for low to high-light plants depending on tank depth. IP67 waterproof rating.',
        tags: ['led', 'planted-tank', 'app-controlled', 'programmable', 'full-spectrum'],
      },
    }),
    prisma.product.create({
      data: {
        name: 'Seachem Flourite Black',
        brand: 'Seachem',
        category: ProductCategory.SUBSTRATE,
        priceRange: PriceRange.MID_RANGE,
        rating: 4.4,
        description: 'Specially fracted clay substrate for planted aquariums. Porous structure provides surface area for beneficial bacteria and root growth. Never needs replacing. Rinse thoroughly before use (very dusty). May temporarily cloud water.',
        tags: ['planted-tank', 'clay', 'permanent', 'root-growth'],
      },
    }),
    prisma.product.create({
      data: {
        name: 'API Freshwater Master Test Kit',
        brand: 'API',
        category: ProductCategory.TESTING,
        priceRange: PriceRange.BUDGET,
        rating: 4.8,
        description: 'Essential liquid test kit for monitoring pH (6.0-7.6), high range pH (7.4-8.8), ammonia (0-8 ppm), nitrite (0-5 ppm), and nitrate (0-160 ppm). More accurate than test strips. Includes test tubes, solutions, and color charts.',
        tags: ['essential', 'water-testing', 'beginner', 'liquid-test', 'accurate'],
      },
    }),
    prisma.product.create({
      data: {
        name: 'Seachem Prime',
        brand: 'Seachem',
        category: ProductCategory.WATER_TREATMENT,
        priceRange: PriceRange.BUDGET,
        rating: 4.9,
        description: 'Complete water conditioner that removes chlorine and chloramine, detoxifies ammonia, nitrite, and nitrate for 24-48 hours. Concentrated formula (5ml treats 50 gallons). Safe for fish, plants, and invertebrates. Does not affect pH.',
        tags: ['essential', 'water-conditioner', 'beginner', 'concentrated', 'detoxifier'],
      },
    }),
    prisma.product.create({
      data: {
        name: 'Aqueon QuietFlow LED PRO Power Filter',
        brand: 'Aqueon',
        category: ProductCategory.FILTER,
        priceRange: PriceRange.BUDGET,
        rating: 4.3,
        description: 'Hang-on-back filter for tanks 10-75 gallons. LED indicator shows when cartridge needs changing. Multi-stage filtration with mechanical, chemical, and biological media. Quiet operation.',
        tags: ['hob', 'budget', 'led-indicator', 'multi-stage'],
      },
    }),
    prisma.product.create({
      data: {
        name: 'Fluval Spec V Aquarium Kit',
        brand: 'Fluval',
        category: ProductCategory.OTHER,
        priceRange: PriceRange.MID_RANGE,
        rating: 4.5,
        description: '5-gallon nano aquarium kit with integrated filtration and LED lighting. Sleek aluminum housing. Perfect for bettas or small shrimp colonies. Includes pump, filter media, and foam block.',
        tags: ['nano', 'kit', 'betta', 'shrimp', 'all-in-one'],
      },
    }),
  ]);

  const [neon, betta, cory, cherry, angel, discus, amano, gecko, cardinal, bristlenose] = animals;

  await Promise.all([
    prisma.animalCompatibility.create({
      data: {
        animalAId: neon.id,
        animalBId: cory.id,
        level: CompatibilityLevel.COMPATIBLE,
        notes: 'Excellent community tank mates. Tetras occupy mid-water, corydoras stay at bottom. Both peaceful and have similar temperature/pH requirements.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: neon.id,
        animalBId: cherry.id,
        level: CompatibilityLevel.COMPATIBLE,
        notes: 'Great combination. Tetras are peaceful and won\'t bother adult shrimp. Provide plants/moss for shrimp cover. Shrimp help with cleanup.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: betta.id,
        animalBId: neon.id,
        level: CompatibilityLevel.CAUTION,
        notes: 'Can work in tanks 20+ gallons with plenty of plants and hiding spots. Bettas may nip at tetra fins, especially in smaller tanks. Monitor closely.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: betta.id,
        animalBId: cherry.id,
        level: CompatibilityLevel.CAUTION,
        notes: 'Bettas may hunt and eat small shrimp, especially juveniles. Heavily planted tanks with moss improve shrimp survival. Individual betta temperament varies.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: betta.id,
        animalBId: betta.id,
        level: CompatibilityLevel.INCOMPATIBLE,
        notes: 'Male bettas will fight to the death. Never house two males together. Female sororities require experienced keepers and 20+ gallon tanks with many hiding spots.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: angel.id,
        animalBId: neon.id,
        level: CompatibilityLevel.CAUTION,
        notes: 'Adult angelfish may eat small tetras that fit in their mouths. Best if raised together from young. Larger tanks (40+ gallons) with dense planting reduce predation risk.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: cory.id,
        animalBId: cherry.id,
        level: CompatibilityLevel.COMPATIBLE,
        notes: 'Both peaceful bottom dwellers. Corydoras won\'t bother shrimp. Provide hiding spots for shrimp molting. Both appreciate similar water conditions.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: neon.id,
        animalBId: cardinal.id,
        level: CompatibilityLevel.COMPATIBLE,
        notes: 'Can school together peacefully. Both occupy similar mid-water space. Cardinals prefer slightly warmer, more acidic water. School of 6+ of each species recommended.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: cory.id,
        animalBId: bristlenose.id,
        level: CompatibilityLevel.COMPATIBLE,
        notes: 'Excellent bottom-dwelling combination. Both peaceful algae eaters with different feeding behaviors. Ensure adequate food for both species.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: cherry.id,
        animalBId: amano.id,
        level: CompatibilityLevel.COMPATIBLE,
        notes: 'Both peaceful shrimp species. Amanos are larger and won\'t compete directly. Excellent algae-eating team. Ensure adequate biofilm and supplemental feeding.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: angel.id,
        animalBId: cherry.id,
        level: CompatibilityLevel.INCOMPATIBLE,
        notes: 'Angelfish will eat cherry shrimp, especially juveniles. Even adult shrimp are at risk. Not recommended unless you accept shrimp as live food.',
      },
    }),
    prisma.animalCompatibility.create({
      data: {
        animalAId: discus.id,
        animalBId: neon.id,
        level: CompatibilityLevel.INCOMPATIBLE,
        notes: 'Discus require much higher temperatures (82-88°F) than neon tetras prefer (68-79°F). Discus may also eat small tetras. Incompatible temperature requirements.',
      },
    }),
  ]);

  console.log('Seed complete!');
  console.log(`  Animals: ${animals.length}`);
  console.log(`  Plants: ${plants.length}`);
  console.log(`  Products: 8`);
  console.log(`  Compatibility rules: 12`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
